<a href="https://colab.research.google.com/github/Qaiserfarooq285/Labtasks/blob/main/quiz2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Alina Maryam Mughal

FA24-RAI-002

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('/content/reviews_dataset.csv')

In [3]:
data.columns

Index(['news', 'type'], dtype='object')

In [4]:
data.head()

news      type
0  China had role in Yukos split-up\n \n China le...  business
1  Oil rebounds from weather effect\n \n Oil pric...  business
2  Indonesia 'declines debt freeze'\n \n Indonesi...  business
3  $1m payoff for former Shell boss\n \n Shell is...  business
4  US bank in $515m SEC settlement\n \n Five Bank...  business

Removing Non Alphabatic

In [8]:

import re

def drop_non_alphabets(text):
  text = re.sub("[^a-zA-Z]", " ", str(text))  # Replace non-alphabetic characters with spaces
  words = text.split()  # Split the text into words
  filtered_words = [word for word in words if word.isalpha()]  # Keep only alphabetic words
  return ' '.join(filtered_words)  # Join the words back into a string

data['news'] = data['news'].apply(drop_non_alphabets)  # Apply the function to the 'news' column

 Tokenization

In [10]:
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import sent_tokenize

# Convert the 'news' column to string type to ensure compatibility with sent_tokenize
data['news'] = data['news'].astype(str)
data['news'] = data['news'].apply(sent_tokenize)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [13]:
print(data['news'][0])

['China had role in Yukos split up China lent Russia bn bn to help the Russian government renationalise the key Yuganskneftegas unit of oil group Yukos it has been revealed The Kremlin said on Tuesday that the bn which Russian state bank VEB lent state owned Rosneft to help buy Yugansk in turn came from Chinese banks The revelation came as the Russian government said Rosneft had signed a long term oil supply deal with China The deal sees Rosneft receive bn in credits from China s CNPC According to Russian newspaper Vedomosti these credits would be used to pay off the loans Rosneft received to finance the purchase of Yugansk Reports said CNPC had been offered of Yugansk in return for providing finance but the company opted for a long term oil supply deal instead Analysts said one factor that might have influenced the Chinese decision was the possibility of litigation from Yukos Yugansk s former owner if CNPC had become a shareholder Rosneft and VEB declined to comment The two companies 

lemmitization

In [ ]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmitizer = WordNetLemmatizer()
def lemmitize_words(text):
    return " ".join([lemmitizer.lemmatize(word,pos='v') for word in text.split()])

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
def lemmatize_sentences(sentences):
    lemmatized_sentences = []
    for sentence in sentences:
        lemmatized_sentence = " ".join([lemmitizer.lemmatize(word, pos='v') for word in sentence.split()])
        lemmatized_sentences.append(lemmatized_sentence)
    return lemmatized_sentences
data['news'] = data['news'].apply(lemmatize_sentences)

In [ ]:
first_row_sentences = data['news'][0]
print(first_row_sentences[0])

["['China role Yukos China lend Russia help Russian government renationalise key Yuganskneftegas unit oil group Kremlin say Tuesday Russian state bank VEB lend Rosneft help buy Yugansk turn come Chinese revelation come Russian government say Rosneft sign oil supply deal deal see Rosneft receive credit According Russian newspaper credit would use pay loan Rosneft receive finance purchase Reports say CNPC offer Yugansk return provide finance company opt oil supply deal Analysts say one factor might influence Chinese decision possibility litigation former CNPC become Rosneft VEB decline two company agree say Russian oil official Sergei nothing unusual five six announcements help explain relatively unknown able finance surprise purchase Yugansk sell auction last year help Yukos pay part bill unpaid tax embattle Russian oil giant previously file bankruptcy protection US court attempt prevent force sale main production Yugansk sell little know shell company turn buy Yukos claim downfall puni

bigram

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

X = data['news'].apply(lambda sentences: ' '.join(sentences))

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Create and fit the CountVectorizer with bigrams
cv = CountVectorizer(ngram_range=(2,2))
X_train_n_gram = cv.fit_transform(X_train)
X_test_n_gram = cv.transform(X_test)

# Create and fit the RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_n_gram,y_train)

# Make predictions
y_pred = rf.predict(X_test_n_gram)

# Calculate and print the accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Calculate and print the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.8539325842696629
Confusion Matrix:
[[108   1   3   2   1]
 [  9  46   0  15   2]
 [  1   1  68   6   0]
 [  1   0   0 101   0]
 [ 15   4   0   4  57]]


triigram

In [24]:
# Import necessary libraries
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

X = data['news'].apply(lambda sentences: ' '.join(sentences))

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Create and fit the CountVectorizer with bigrams
cv = CountVectorizer(ngram_range=(3,3))
X_train_n_gram = cv.fit_transform(X_train)
X_test_n_gram = cv.transform(X_test)

# Create and fit the RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_n_gram,y_train)

# Make predictions
y_pred = rf.predict(X_test_n_gram)

# Calculate and print the accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Calculate and print the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)


Accuracy: 0.8157303370786517
Confusion Matrix:
[[103   1   2   7   2]
 [ 15  42   0  14   1]
 [  7   1  62   6   0]
 [  0   0   0 102   0]
 [ 14   1   1  10  54]]


random forest

In [26]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split # Import train_test_split
from sklearn.metrics import accuracy_score


# Assuming X and Y are your features and target variable respectively
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42) # Split data

# Create a Random Forest Classifier with 150 trees
rf = RandomForestClassifier(n_estimators=150)

# Fit the model to the training data
rf.fit(X_train_n_gram, y_train)

# Make predictions on the testing data
y_pred = rf.predict(X_test_n_gram)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7932584269662921
