<a href="https://colab.research.google.com/github/Qaiserfarooq285/Labtasks/blob/main/quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Quiz-2**

Perform following tasks on the provided Reviews Dataset.
* Drop words if not alphabets.
* Tokenize the sentence.
* Perform lemitization.
* Vectorize using bigram and trigram techniques.
* Apply Random Forest algorithm with 150 trees.
* Evaluate overall accuracy of the model and class-wise precision .

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv('/content/reviews_dataset.csv')

In [ ]:
data.columns

Index(['news', 'type'], dtype='object')

In [ ]:
data.head()

news      type
0  [["['China role Yukos China lend Russia help R...  business
1  [["['Oil rebound weather effect Oil price reco...  business
2  [["['Indonesia debt Indonesia longer need debt...  business
3  [["['payoff former Shell boss Shell pay chief ...  business
4  [["['US bank SEC settlement Five Bank America ...  business

# removing non numerical

In [ ]:
import pandas as pd
import re

def drop_non_alphabets(text):

  words = text.split()
  filtered_words = [word for word in words if word.isalpha()]
  return ' '.join(filtered_words)

# Assuming your DataFrame is called 'data' and the column is called 'news'
data['news'] = data['news'].apply(drop_non_alphabets)

# removing stopwords

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

def remove_stopwords(sentences):
  stop_words = set(stopwords.words('english'))
  filtered_sentences = []
  for sentence in sentences:
    words = sentence.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    filtered_sentence = " ".join(filtered_words)
    filtered_sentences.append(filtered_sentence)
  return filtered_sentences

data['news'] = data['news'].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


# tokenization

In [ ]:
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize

# Ensure 'news' column contains strings before applying sent_tokenize
data['news'] = data['news'].astype(str).apply(sent_tokenize)

# Access sentences in a particular cell
sentences_in_row_1 = data['news'][1]
for sentence in sentences_in_row_1:
    print(sentence)

["['Oil rebound weather effect Oil price recover Asian trade fall New York milder winter weather across winter temperatures stay relatively high northern barrel light crude end Monday However crude price rebound rise barrel February trade Brent crude suspend public price fell Far milder temperatures expect continue northern part US next days analysts say price oil may fall even decline heel say ABN AMRO analyst John winter Eventually get another cold Despite fall barrel record highs reach late price crude oil remain almost higher Prices rise last week militant attack capital Saudi briefly renew fear supply chain might break lead crude market panic fear essentially since say Deborah senior economist energy SG Securities in']"]


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


# lemmitiazation

In [ ]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmitizer = WordNetLemmatizer()
def lemmitize_words(text):
    return " ".join([lemmitizer.lemmatize(word,pos='v') for word in text.split()])

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
def lemmatize_sentences(sentences):
    lemmatized_sentences = []
    for sentence in sentences:
        lemmatized_sentence = " ".join([lemmitizer.lemmatize(word, pos='v') for word in sentence.split()])
        lemmatized_sentences.append(lemmatized_sentence)
    return lemmatized_sentences

data['news'] = data['news'].apply(lemmatize_sentences)

In [ ]:
first_row_sentences = data['news'][0]
print(first_row_sentences[0])

["['China role Yukos China lend Russia help Russian government renationalise key Yuganskneftegas unit oil group Kremlin say Tuesday Russian state bank VEB lend Rosneft help buy Yugansk turn come Chinese revelation come Russian government say Rosneft sign oil supply deal deal see Rosneft receive credit According Russian newspaper credit would use pay loan Rosneft receive finance purchase Reports say CNPC offer Yugansk return provide finance company opt oil supply deal Analysts say one factor might influence Chinese decision possibility litigation former CNPC become Rosneft VEB decline two company agree say Russian oil official Sergei nothing unusual five six announcements help explain relatively unknown able finance surprise purchase Yugansk sell auction last year help Yukos pay part bill unpaid tax embattle Russian oil giant previously file bankruptcy protection US court attempt prevent force sale main production Yugansk sell little know shell company turn buy Yukos claim downfall puni

In [ ]:
from sklearn.preprocessing import LabelEncoder

#X = df.drop('sentiment', axis=1)
X = data['news']
Y = data['type']

print(X)
print(Y)

encoder = LabelEncoder()
Y = encoder.fit_transform(Y)

print(Y)

0       China had role in Yukos split-up\n \n China le...
1       Oil rebounds from weather effect\n \n Oil pric...
2       Indonesia 'declines debt freeze'\n \n Indonesi...
3       $1m payoff for former Shell boss\n \n Shell is...
4       US bank in $515m SEC settlement\n \n Five Bank...
                              ...                        
2220    Microsoft launches its own search\n \n Microso...
2221    Warnings about junk mail deluge\n \n The amoun...
2222    Microsoft gets the blogging bug\n \n Software ...
2223    Gamers snap up new Sony PSP\n \n Gamers have b...
2224    Apple laptop is 'greatest gadget'\n \n The App...
Name: news, Length: 2225, dtype: object
0       business
1       business
2       business
3       business
4       business
          ...   
2220        tech
2221        tech
2222        tech
2223        tech
2224        tech
Name: type, Length: 2225, dtype: object
[0 0 0 ... 4 4 4]


# Bigram

In [ ]:

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# Assuming you have X and Y defined

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=42)

# Create a CountVectorizer with only bigrams
cv = CountVectorizer(ngram_range=(2, 2))  # Changed to (2, 2) for bigrams only

# Fit and transform the training data
X_train_n_gram = cv.fit_transform(X_train)

# Transform the testing data
X_test_n_gram = cv.transform(X_test)

# Initialize a RandomForestClassifier
rf = RandomForestClassifier()

# Fit the model on the training data
rf.fit(X_train_n_gram, y_train)

# Make predictions on the test data
y_pred = rf.predict(X_test_n_gram)

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.8797127468581688
[[134   1   4   2   1]
 [ 14  69   0  11   0]
 [  3   0  83   8   1]
 [  0   0   0 121   1]
 [ 14   2   0   5  83]]


# Trigram

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# Assuming you have X and Y defined

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=42)

# Create a CountVectorizer with only trigrams
cv = CountVectorizer(ngram_range=(3, 3))  # Changed to (3, 3) for trigrams only

# Fit and transform the training data
X_train_n_gram = cv.fit_transform(X_train)

# Transform the testing data
X_test_n_gram = cv.transform(X_test)

# Initialize a RandomForestClassifier
rf = RandomForestClassifier()

# Fit the model on the training data
rf.fit(X_train_n_gram, y_train)

# Make predictions on the test data
y_pred = rf.predict(X_test_n_gram)

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.7791741472172352
[[117   1   3  18   3]
 [  9  59   0  25   1]
 [  6   1  72  16   0]
 [  0   0   0 122   0]
 [ 18   4   2  16  64]]


# 150 tree randomforest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Initialize a RandomForestClassifier with 150 trees
rf = RandomForestClassifier(n_estimators=150)

# Fit the model on the training data
rf.fit(X_train_n_gram, y_train)

# Make predictions on the test data
y_pred = rf.predict(X_test_n_gram)
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Print accuracy
print("Accuracy:", accuracy)

Accuracy: 0.7935368043087971


# **Evaluating the overall accuarcy**

We have 87 accuracy on bigram and 77 on trigram and 79 on random forest